### ISSUE TITLE
Non-english keyboard layout - programs shortcuts doesn't work (CTRL+C etc...)

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1309]
## Describe the bug
When keyboard layout is russian (i suspect any language which is not english) - any program shortcuts doesn't work (CTRL+C / CTRL+V / CTRL+S etc)

## To Reproduce
Any program to my knowledge, for example Sulbime text 3

## Expected behavior
All shortcuts of a program should work regardless of keyboard layout language selected.

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.1.8-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.10.1
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 8.3.0
tk: Qt 5.12.3
dm: LightDM

### Distro & Version
Arch / Manjaro Deepin

### Related package version
No idea

### Additional context
This started somewhere in course of 2 months from now, in cycle of moving to deepin-kwin etc.

@BLumia 
Please take a look at this, seems to me like pretty serious bug for anyone - because it limits workflow of people who use more than one keyboard layouts.

**Comment by BLumia** [comment]
Sorry I am not familiar with how ime works..

cc @electricface

**Comment by hualet** [comment]
I think there's an old discussion here, but without any conclusion..

**Comment by keybreak** [comment]
@hualet
What do you mean?
It's still a problem

**Comment by keybreak** [comment]
Kinda hard to live without Ctrl+Z

**Comment by hsabzehmeidani** [comment]
Hi @keybreak , @hualet 
This issue was solved for my keyboard layout:
1. Change the system language (from American English) to Russian.
2. Apply changes and updates to the system.
After the system is restarted, shortcuts are activated for Russian keyboard layout.
Then restore the system language to its primary state.
Now shortcuts work well on both of the keyboards layout.

**Comment by keybreak** [comment]
@hsabzehmeidani 
For me it doesn't work:
1. When i switch to russian system language after reboot for example Sublime Text Ctrl + Z still doesn't work for russian, but works for english

2. When i switch back to english after next reboot still same goes, Ctrl + Z doesn't work for russian language, and works for english

**Comment by hsabzehmeidani** [comment]
Hi @keybreak 
Ok, Sometimes it works well, sometimes not!
However, we do the following steps to solve the problem in the Sublime text editor:
- Open "Sublime Text 3" and Go to menu "Preferences" > "Key Bindings"
- Write the following content in the "Default (Linux).sublime-keymap __ User" file
- Instead of the following English characters (n , o, s, w, q, z, ...), put the Russian character equivalent on the keyboard layout.
- Save the file.
```txt
[
	// File
	{ "keys": ["ctrl+n"], "command": "new_file" },
	{ "keys": ["ctrl+o"], "command": "prompt_open_file" },
	{ "keys": ["ctrl+s"], "command": "save" },
	{ "keys": ["ctrl+shift+s"], "command": "prompt_save_as" },
	{ "keys": ["ctrl+shift+n"], "command": "new_window" },
	{ "keys": ["ctrl+shift+w"], "command": "close_window" },
	{ "keys": ["ctrl+w"], "command": "close" },
	{ "keys": ["ctrl+q"], "command": "exit" },

	// Edit
	{ "keys": ["ctrl+z"], "command": "undo" },
	{ "keys": ["ctrl+y"], "command": "redo_or_repeat" },
	{ "keys": ["ctrl+x"], "command": "cut" },
	{ "keys": ["ctrl+c"], "command": "copy" },
	{ "keys": ["ctrl+v"], "command": "paste" },
	{ "keys": ["ctrl+shift+v"], "command": "paste_and_indent" },
	{ "keys": ["alt+/"], "command": "auto_complete" },
	{ "keys": ["alt+/"], "command": "replace_completion_with_auto_complete", "context":
		[
			{ "key": "last_command", "operator": "equal", "operand": "insert_best_completion" },
			{ "key": "auto_complete_visible", "operator": "equal", "operand": false },
			{ "key": "setting.tab_completion", "operator": "equal", "operand": true }
		]
	},

	// Selection
	{ "keys": ["ctrl+shift+l"], "command": "split_selection_into_lines" },
	{ "keys": ["ctrl+a"], "command": "select_all" },
	{ "keys": ["ctrl+l"], "command": "expand_selection", "args": {"to": "line"} },
	{ "keys": ["ctrl+d"], "command": "find_under_expand" },
	{ "keys": ["ctrl+shift+m"], "command": "expand_selection", "args": {"to": "brackets"} },
	{ "keys": ["ctrl+shift+j"], "command": "expand_selection", "args": {"to": "indentation"} },
	{ "keys": ["ctrl+shift+a"], "command": "expand_selection", "args": {"to": "tag"} },

	// Find
	{ "keys": ["ctrl+f"], "command": "show_panel", "args": {"panel": "find", "reverse": false} },
	{ "keys": ["ctrl+i"], "command": "show_panel", "args": {"panel": "incremental_find", "reverse": false} },
	{ "keys": ["ctrl+h"], "command": "show_panel", "args": {"panel": "replace", "reverse": false} },
	{ "keys": ["ctrl+shift+h"], "command": "replace_next" },
	{ "keys": ["ctrl+e"], "command": "slurp_find_string" },
	{ "keys": ["ctrl+shift+e"], "command": "slurp_replace_string" },
	{ "keys": ["ctrl+shift+f"], "command": "show_panel", "args": {"panel": "find_in_files"} },

	// View
	{ "keys": ["ctrl+`"], "command": "show_panel", "args": {"panel": "console", "toggle": true} },

	// Goto
	{ "keys": ["ctrl+p"], "command": "show_overlay", "args": {"overlay": "goto", "show_files": true} },
	{ "keys": ["ctrl+r"], "command": "show_overlay", "args": {"overlay": "goto", "text": "@"} },
	{ "keys": ["ctrl+shift+r"], "command": "goto_symbol_in_project" },
	{ "keys": ["ctrl+g"], "command": "show_overlay", "args": {"overlay": "goto", "text": ":"} },
	{ "keys": ["ctrl+m"], "command": "move_to", "args": {"to": "brackets"} },

	// Tools
	{ "keys": ["ctrl+shift+p"], "command": "show_overlay", "args": {"overlay": "command_palette"} },
	{ "keys": ["ctrl+b"], "command": "build" },
	{ "keys": ["ctrl+shift+b"], "command": "build", "args": {"select": true} },
	{ "keys": ["ctrl+alt+q"], "command": "toggle_record_macro" },
	{ "keys": ["ctrl+alt+shift+q"], "command": "run_macro" },

	// Project
	{ "keys": ["ctrl+alt+p"], "command": "prompt_select_workspace" },
]
```
like this image:
![subime-text-3](https://user-images.githubusercontent.com/46417001/61578874-8e7f9e00-ab12-11e9-868b-50f3a0868458.png)

**Comment by keybreak** [comment]
@hsabzehmeidani 
Thx, i know this would work (for example i've done it with Renoise), problem is that it's ALL programs, and this is not normal behavior by default...

Fixing all programs like that would be insane, it's clearly system-level issue...

So i really would like @BLumia & @hualet to fix it once and for good, so that it won't be an issue for future multilingual users.

**Comment by keybreak** [comment]
That's really hard to use sometimes, like even terminal simple shortcuts like Ctrl + Shift + C / Ctrl + Shift + V or Q to close results of journalctl -p3 -xb doesn't work when you switched to non-english layout.

This is getting really hard to work with (sometimes you don't even remember and stuck on wtf is wrong), please fix this and force all programs shortcuts to always use ENGLISH keyboard layout, no matter which language to type with is currently selected.

Like i've said - it wasn't that way before.

**Comment by aquaminer** [comment]
+1, don't work with ukrainian locale

**Comment by Deniskore** [comment]
+1
The issue still not fixed in 2020

**Comment by mafzalzadeh** [comment]
Is there any update ?

**Comment by Misioka** [comment]
Will it be fixed? Cannot use DeepIn at all without working shortcuts :(.

**Comment by grigoriy-a** [comment]
Still an issue in Deepin 20/1003 CE

**Comment by tukusejssirs** [comment]
I am just a passer-by. I experience the very same issue, but I don’t use Deepin.

I have installed Manjaro Gnome (Nibia 20.2.1), Slovak locale for the GUI and Slovak + English (UK) keyboard layouts (KBLOs). Note that I have never ever used or installed Manjaro distro.

I too use Sublime Text 3 and the shortcuts on Slovak KBLO sort of behave like if I’ve used English KBLO, for example: when I need to zoom out (<kbd>C</kbd>+<kbd>-</kbd>), I need to press <kbd>Ctrl</kbd>+<kbd>-</kbd> on Slovak KBLO (<kbd>-</kbd> is localated where <kbd>/</kbd> is located on English KBLO).

As I don’t use Deepin and still experience this issue, I think that the issue is one of Manjaro.

Would anyone be able and willingful to raise this issue upstream?
