### ISSUE TITLE
White Line of Pixels When Scaling

### ISSUE THREAD

**Issue by alexwender1** [linuxdeepin/developer-center#1352]
## Describe the bug
The user uses the display range of 1.5, on a 1080p screen (nice for use). When you switch to the 1.25 scale, the white line disappears... But the icons and expressions are not in an appropriate size on that screen size.

I asked them to change the wallpaper (bigger size), but the problem persists.

On my screen, with the resolution of 768p, I use it on the normal 1.0 display scale. When you change the scale to 1.25, the white line appears.

## Screenshots
(1920x1080) The user uses the 1.5 display scale to be pleasant to use; but the white line at the bottom (and on the right side) of the screen is present:
![66610440_2297811876973947_3797861278580473856_n](https://user-images.githubusercontent.com/45263160/60738896-3e131880-9f36-11e9-9758-90bb32335d25.jpg)

(1366x768) On my computer, using the 1.25 scale, the white line of pixels appears. At 1.0 scale, I have no problems.
![photo4972004135448717352](https://user-images.githubusercontent.com/45263160/60738902-41a69f80-9f36-11e9-874e-e22f454f28aa.jpg)

### Distro & Version
Deepin 15.10.2 Lion

**Comment by Mark-AAAA** [comment]
That's absolutely true!

**Comment by Mark-AAAA** [comment]
I had the same issue, but after latest updates on arch, it got fixed!
What is your GPU and your currently installed drivers?

**Comment by keybreak** [comment]
@BLumia @zccrs 
Same bug reported by Manjaro Deepin user **hackmonker**, on same resolution of **1366x768**:
![image](https://user-images.githubusercontent.com/47599989/61046358-968a6000-a3e5-11e9-8275-8df755d48f32.png)

**inxi -Fxxz**
```
System:
  Host: hackmonker-pc Kernel: 4.19.56-1-MANJARO x86_64 bits: 64 compiler: gcc 
  v: 9.1.0 Desktop: Deepin 15.10.1 tk: Qt 5.13.0 wm: DeepinWM dm: LightDM 
  Distro: Manjaro Linux 
Machine:
  Type: Desktop Mobo: BIOSTAR model: H81MHV3 v: 5.0 serial: <filter> 
  BIOS: American Megatrends v: 4.6.5 date: 05/21/2014 
CPU:
  Topology: Dual Core model: Intel Pentium G3260 bits: 64 type: MCP 
  arch: Haswell rev: 3 L2 cache: 3072 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 13189 
  Speed: 799 MHz min/max: 800/3300 MHz Core speeds (MHz): 1: 799 2: 799 
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics 
  vendor: Biostar Microtech Intl Corp driver: i915 v: kernel bus ID: 00:02.0 
  chip ID: 8086:0402 
  Display: x11 server: X.Org 1.20.5 driver: intel unloaded: modesetting 
  alternate: fbdev,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: Mesa DRI Intel Haswell Desktop v: 4.5 Mesa 19.1.1 
  compat-v: 3.0 direct render: Yes 
Audio:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio 
  driver: snd_hda_intel v: kernel bus ID: 00:03.0 chip ID: 8086:0c0c 
  Device-2: Intel 8 Series/C220 Series High Definition Audio 
  vendor: Biostar Microtech Intl Corp driver: snd_hda_intel v: kernel 
  bus ID: 00:1b.0 chip ID: 8086:8c20 
  Sound Server: ALSA v: k4.19.56-1-MANJARO 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: Biostar Microtech Intl Corp driver: r8168 v: 8.047.01-NAPI 
  port: e000 bus ID: 02:00.0 chip ID: 10ec:8168 
  IF: enp2s0 state: down mac: <filter> 
  Device-2: Realtek RTL8188EUS 802.11n Wireless Network Adapter type: USB 
  driver: r8188eu bus ID: 1-2:3 chip ID: 0bda:8179 
  IF: wlp0s20u2 state: down mac: <filter> 
  IF-ID-1: enp0s20u3 state: unknown speed: N/A duplex: N/A mac: <filter> 
Drives:
  Local Storage: total: 1.14 TiB used: 494.51 GiB (42.5%) 
  ID-1: /dev/sda vendor: Seagate model: ST250DM000-1BD141 size: 232.89 GiB 
  speed: 6.0 Gb/s serial: <filter> 
  ID-2: /dev/sdb type: USB vendor: Toshiba model: MQ04ABF100 size: 931.51 GiB 
  serial: <filter> 
Partition:
  ID-1: / size: 99.91 GiB used: 8.04 GiB (8.1%) fs: ext4 dev: /dev/sda3 
  ID-2: swap-1 size: 8.28 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda4 
Sensors:
  System Temperatures: cpu: 47.0 C mobo: N/A 
  Fan Speeds (RPM): N/A 
Info:
  Processes: 167 Uptime: 47m Memory: 3.78 GiB used: 1.74 GiB (46.0%) 
  Init: systemd v: 242 Compilers: gcc: 9.1.0 Shell: bash v: 5.0.7 
  running in: deepin-terminal inxi: 3.0.34 
```
(c) https://forum.manjaro.org/t/green-dotted-line-in-new-deepin-install/94420

**Comment by zccrs** [comment]
Thank you. We already know this bug, but we can't solve it in a short time.

**Comment by juancastellano115** [comment]
Hello I know Its a little bit late but I fixed it by updating my Nvidia drivers!
sudo apt-get install nvidia-driver

**Comment by BLumia** [comment]
I've heard of @zccrs resolved this issue in the internal unreleased codebase, sadly it's still not sure when the v20 codebase will be available to public :(
