### ISSUE TITLE
Transparent background misplaced

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1754]
## Describe the bug

The transparent background in some applications is not in the correct place.
## To Reproduce

1. Open notification panel in Arch/Manjaro
2. See the result
Or,
1. Open Deepin terminal.
2. Make sure you have enabled "blur background" from the settings.
3. See the result.

## Expected behavior

The transparent background should be in the correct place.
## Screenshots

![Screen Capture_select-area_20200601064456](https://user-images.githubusercontent.com/33563064/83366869-8b606a00-a3d3-11ea-8a7b-d9f840bbc46e.png)
![Screen Capture_select-area_20200601064717](https://user-images.githubusercontent.com/33563064/83366913-c367ad00-a3d3-11ea-815b-59380c88fbe0.png)

### Distro & Version

Manjaro 20.0.2
DDE v20
### Related package version

`kwin v5.18.5-1`
`deepin-kwin v5.0.14.1-3`
`deepin-dock v5.1.0.9-1`
`deepin-terminal v5.0.4.1-1`
### Additional context

This bug occurs only in Manjaro/Arch. It does not occur in Deepin OS.

**Comment by felixonmars** [comment]
I cannot reproduce the issue in Notification Center.

deepin-terminal in [community-testing] should have this fixed.

**Comment by SiamSami** [comment]
@felixonmars It's happening on kwin only. Not on deepin-mutter.

**Comment by gardotd426** [comment]
@felixonmars I can reproduce the issue as well. It's very subtle, but it's there. 

Well, actually it's not subtle at all. 

But anyway, it's not fixed on testing either, first of all, deepin terminal now has NO blur at all, so I guess you could say that's fixed, but not really (and yes, blur is on elsewhere, it's working perfectly fine in the panel). 

And the notifications are still not showing correct blur:

![deepinblurbug1](https://user-images.githubusercontent.com/54234607/83451410-e2425f80-a424-11ea-9059-9c0aea3a94ce.png)

**Comment by gardotd426** [comment]
I just noticed that notifications (not the notification center, actual notifications) also show blur correctly. It's just the terminal and the notification center, so far. Like I said, I went to community-testing (and regular core testing as it's required to even run deepin terminal, since Qt 5.15 is a dependency), and updated the system, and this is the result.

**Comment by gardotd426** [comment]
It's really a shame about the color scheme too, because with the blur fixed now it looks absolutely gorgeous, but I can't stand that ugly green text color, it looks awful. And what's weird is you can tell that it's SOMEWHAT respecting my colorscheme, the blue and grey are from my set colorscheme, but it's overriding it for the green and light-grey (off white?).

**Comment by felixonmars** [comment]
I think I can reproduce the notification center one now, although I don't know what has changed :/

I still cannot reproduce the terminal one.

![2020-06-02-043637-92eed2](https://user-images.githubusercontent.com/1006477/83452099-b1951100-a48a-11ea-847f-1c0e32a4b1f4.png)

**Comment by felixonmars** [comment]
I agree on the color schemas thing too and that's exactly why I still don't want to move it to [community] yet. They are going to do another release soon if I am not mistaken though.

**Comment by gardotd426** [comment]
No you're right about the terminal, I've got that fixed. Although there is now NO way to edit the Deepin Terminal theme (the only "Theme" option is the same old "Light," "Dark," and "System" used for the titlebar and window decorations, not the terminal itself), which is absolutely not how it used to be. 

Even on the previous version before this community-testing update, deepin-terminal at least respected my colorscheme set for all my other terminals. But if you look, the colorscheme reported by deepin-terminal for my and your terminal is exactly the same.

![blurbug](https://user-images.githubusercontent.com/54234607/83452366-9395c500-a426-11ea-9333-8a33ee493dbe.png)

But yeah, man that could be SO gorgeous if they would fix the stupid color scheme. 

But yeah I think we're on the same page, both of us goofed there for a moment. I fixed my blur issue in the terminal, and now you say you can reproduce @SiamSami's Notification center blur issue (as can I).

**Comment by gardotd426** [comment]
And yeah I see now what you said about the terminal scheme, it came through the same time I was typing my above comment.

**Comment by gardotd426** [comment]
Also yes, they seem to be releasing updates quite regularly, so that's at least a good sign as long as the remaining show-stopper issues get fixed (like this, the notification stuff, and the fact that the window effect breaks and the black borders come back like all the time, I'm having to restart kwin multiple times a day which is no big deal, but still kind of unacceptable for a stable DE).

**Comment by gardotd426** [comment]
Well damn, @felixonmars, it seems that the new update shows that their plan is to not allow you to change the theme of the terminal, but just to actually have the terminal use the two Deepin-approved themes of "light" and "dark, because now it's not even respecting the two colors it was, and all coloring is fully controlled by Deepin:

![terminal1](https://user-images.githubusercontent.com/54234607/83466368-e7170b80-a444-11ea-83e4-cca54f42f9ab.png)

Contrast that above from just a couple hours ago before the update to the newest version, where my colors were only have respected, now you see they have their own color scheme set. This really sucks. It's bad enough that their EULA is completely, 100 percent incompatible with the GPL v3 they license everything under, but now it's looking to turn into a walled-garden situation.

**Comment by SiamSami** [comment]
Any update on this?

**Comment by SiamSami** [comment]
About the notification panel, I think the problem is related to `kwin` as this problem doesn't occur in Deepin OS.

Perhaps some `kwin` window rules can fix it?

**Comment by SiamSami** [comment]
@felixonmars Weirdly enough, if we run dde-dock from the terminal then we don't see this bug.
![Screen Capture_select-area_20200625211434](https://user-images.githubusercontent.com/33563064/85747596-3ccf9280-b729-11ea-8cba-97df1d3a9acd.png)
![Screen Capture_select-area_20200625211603](https://user-images.githubusercontent.com/33563064/85747630-43f6a080-b729-11ea-8a76-85db32bbcb3b.png)

**Comment by SiamSami** [comment]
@felixonmars Another thing I noticed is that when kwin is runned automatically by the DE, it is runned with this command `kwin_x11 -platform dde-kwin-xcb:appFilePath=/usr/bin/kwin_no_scale`
![Screen Capture_deepin-system-monitor_20200625213348](https://user-images.githubusercontent.com/33563064/85750511-95a02a80-b72b-11ea-8aaf-00e1018a69d0.png)

**Comment by felixonmars** [comment]
Yes that's correct (which is what kwin_no_scale does)

**Comment by SiamSami** [comment]
@gardotd426 Deepin OS uses kwin as well but for some reason, we don't see this issue there.

**Comment by SiamSami** [comment]
Can anyone share the `kwinrc` file from Deepin OS?

**Comment by SiamSami** [comment]
The same issue can be seen in the properties dialog of files and folders.
![Screen Capture_select-area_20200630215954](https://user-images.githubusercontent.com/33563064/86149028-3708f100-bb1d-11ea-8e9c-787db5812423.png)

**Comment by justforlxz** [comment]
We will use the native kwin blur plugin for non-deepin users.
