### ISSUE TITLE
Cpu usage ramps up while hovering over DDE Dock plugins or icons

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1763]
## Describe the bug
Cpu usage ramps up significantly while I am hovering over icons or dock plugins.

## To Reproduce
**Steps to reproduce the behavior:**
Hover over icons or plugins on the dock while watching the cpu usage via system monitor apps or desktop wigdets, terminal, etc.

## Expected behavior
Cpu usage shouldn't change significantly.

## Video
https://sendvid.com/tij1czcv

**Related error:**
`[Warning] [                                                         0] requestActivate() called for  QWidgetWindow(0x1019490, name="Dtk::Widget::DArrowRectangleClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.`

![image](https://user-images.githubusercontent.com/45146702/84501419-2c4a0180-acbf-11ea-83f7-5c99d378105e.png)

### Distro & Version
Linux Deepin 20 Beta

### Related package version
dde-dock v5(5.0.27+c3-1)

**Comment by xmuli** [comment]
Already relayed to dock's team on his behalf.

**Comment by gokhanyildirimlar** [comment]
> Already relayed to dock's team on his behalf.

I didn't find someone else reported this but I can close the issue if it's already reported.

**Comment by gokhanyildirimlar** [comment]
The issue has been solved with the latest public beta.

**Comment by sayoojsamuel** [comment]
@gokhanyildirimlar I'm using dde-dock (5.1.0.14-1) with Deepin 20 beta.  I still have this issue when the CPU usage boosts up when hovering over plugins, applets or unopened pinned apps.   This at times, spawns new dde-dock processes. 

![image](https://user-images.githubusercontent.com/31436104/93247512-047da480-f7ac-11ea-8def-4fe8e48cdd72.png)

It is also noticed that at times dde-dock becomes unresponsive after reaching CPU 100%, by then I'd have to kill the process to reset it to normal.

**Comment by gokhanyildirimlar** [comment]
Why do you even still use Deepin 20 Beta, @sayoojsamuel? There is v1002 now and I don't encounter this issue anymore.

**Comment by sayoojsamuel** [comment]
@gokhanyildirimlar could you help me on how to check out the deepin version?  I update the packages everyday. 
I know that I'm running deepin-wm version 1.9.38-4.   But everytime I run `deepin-wm --version` says `Gala unknown`.  

Thanks!

**Comment by gokhanyildirimlar** [comment]
` cat /etc/os-version` should do it. Major version 20 means you are using Deepin 20, and minor version is more specific. Minor version should be 1002 as it's latest stable release. @sayoojsamuel

**Comment by xmuli** [comment]
@sayoojsamuel @gokhanyildirimlar Later in the dde-control-center, the specific version number will be displayed, Already arranged in the plan

**Comment by sayoojsamuel** [comment]
@xmuli deepin-dock version 5.2.0.14-1 seems to have resolved this problem.  However, this issue was persistant till version 5.1.0.14-1.

**Comment by karthick-kk** [comment]
@sayoojsamuel this issue still persist in current version 5.2.0.14-1. dde-dock continue to use 90-100% cpu
![image](https://user-images.githubusercontent.com/1493364/94815548-49464400-0418-11eb-98e5-d02dd44ac981.png)

**Comment by sayoojsamuel** [comment]
@karthick-kk I can confirm this issue is not resolved.  I'm still unable to find what is triggering this high CPU usage.

**Comment by gokhanyildirimlar** [comment]
I can open the issue again if you want to but the actual topic of this issue has been resolved. Taskbar/dock plugins don't cause jumps on CPU usage anymore. Or do they? Let me know if you want to reopen the issue, @karthick-kk, @sayoojsamuel.

**Comment by karthick-kk** [comment]
@gokhanyildirimlar not sure, is this anyway linked to the memory leak issue https://github.com/linuxdeepin/dde-dock/issues/303
