### ISSUE TITLE
[Bug] Notification icon goes missing automatically

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1779]
## Describe the bug

The notification icon in dde-dock goes missing automatically
## To Reproduce

1. Start Deepin DE
2. If the notification icon is displayed, then wait for some time.
3. The notification should go away automatically.
## Expected behavior

The notification icon should not go away automatically.
## Screenshots

![Screen Capture_select-area_20200625093028](https://user-images.githubusercontent.com/33563064/85650507-812a4680-b6c7-11ea-8be0-1ad5bb46151e.gif)

## Enviroments:
DE: Deepin v20
### Distro & Version

Archlinux with latest updates
### Related package version

`deepin-dock` v5.1.0.11-1
### Additional context

We can bring back the notification icon from the control centre but after some time it will go away again.

**Comment by felixonmars** [comment]
Please try again with deepin-dock 5.1.0.11.20200622-1

**Comment by SiamSami** [comment]
@felixonmars Thanks! It looks like it has been fixed. Closing.

**Comment by alok-1019** [comment]
I have the same issue. The issue still persists.
I am using Ubuntu DDE 20.10.
