### ISSUE TITLE
Minimize button of Deepin apps is broken

### ISSUE THREAD

**Issue by Saduff** [linuxdeepin/developer-center#1823]
## Describe the bug

1. The minimize button only works once. Clicking it next time doesn't do anything.
2. Clicking the minimize button once breaks the maximize button such that the right side of the window is not clickable when maximized.

Related issue: #1521

## To Reproduce

1. Open any Deepin app like control center, terminal, text editor, calendar etc
2. Click the minimize button
3. Bring the app back into focus
4. Click the minimize button again
5. Click the maximize button
6. Try click on the right side of the window or any buttons (minimize, maximize, close)

## Expected behavior

The app should minimize when the button is pressed and it should not break the maximized window such that the right side of the window is not clickable.

## Actual behavior

The minimize button doesn't do anything and it breaks the maximized window.

### 1. Minimize button

![Screen Capture_select-area_20200715144855](https://user-images.githubusercontent.com/11700507/87543367-4d7e8300-c6ad-11ea-942b-ba9f1887b15e.gif)

### 2. Maximized window problem

![Screen Capture_dde-desktop_20200715150111](https://user-images.githubusercontent.com/11700507/87543434-6b4be800-c6ad-11ea-9934-62b5dcbd1f84.gif)

### Distro & Version

Arch Linux with Deepin v20

### Related package version

```
deepin-account-faces 1.0.11-2 (deepin)
deepin-anything 5.0.1-3 (deepin)
deepin-anything-arch 5.0.1-92
deepin-api 5.3.0.3-1 (deepin)
deepin-boot-maker 5.4.8-1 (deepin-extra)
deepin-calendar 5.7.0.3-1 (deepin)
deepin-clone 5.0.3-1 (deepin-extra)
deepin-clutter 1.26.2-3
deepin-cogl 1.22.5-3
deepin-community-wallpapers 1:1.7.7-2 (deepin-extra)
deepin-control-center 5.2.0.20-1 (deepin)
deepin-daemon 5.11.0.17-1 (deepin)
deepin-desktop-base 2:2020.04.12.2-2 (deepin)
deepin-desktop-schemas 5.6.0.12-1 (deepin)
deepin-dock 5.1.0.11.20200622-1 (deepin)
deepin-editor 5.6.21-1 (deepin-extra)
deepin-file-manager 1:5.1.1.25-4 (deepin)
deepin-gtk-theme 2020.06.10-1 (deepin)
deepin-icon-theme 2020.06.30-1 (deepin)
deepin-image-viewer 5.6.3.2-2 (deepin)
deepin-kwin 5.1.0.4-2 (deepin)
deepin-launcher 5.2.0.13-1 (deepin)
deepin-manual 5.0.0-1 (deepin)
deepin-menu 5.0.1-2 (deepin)
deepin-metacity 3.22.24-2
deepin-movie 1:5.7.6.29-1 (deepin-extra)
deepin-music 6.0.1.8-2 (deepin-extra)
deepin-mutter 3.20.38-4
deepin-network-utils 5.1.0.1-1 (deepin)
deepin-picker 5.0.6-1 (deepin-extra)
deepin-polkit-agent 5.2.0.7-1 (deepin)
deepin-polkit-agent-ext-gnomekeyring 0.1.0-2 (deepin)
deepin-qt-dbus-factory 5.2.0.3-1
deepin-qt5integration 5.1.0.3-1 (deepin)
deepin-qt5platform-plugins 5.0.13-1 (deepin)
deepin-screen-recorder 5.8.0.11-3 (deepin-extra)
deepin-screensaver 5.0.3-1 (deepin)
deepin-session-shell 5.1.0.10-1 (deepin)
deepin-session-ui 5.2.0.11-1 (deepin)
deepin-shortcut-viewer 5.0.2-1 (deepin)
deepin-sound-theme 15.10.6-1 (deepin)
deepin-system-monitor 5.6.12-1 (deepin)
deepin-terminal 5.2.11-1 (deepin-extra)
deepin-turbo 0.0.3-2 (deepin)
deepin-voice-note 5.7.11-1 (deepin-extra)
deepin-wallpapers 1:1.7.7-2 (deepin)
deepin-wallpapers-plasma 5.18.5-1
dtkgui 5.2.2.1-1
dtkwidget 5.2.2.2-1
dtkwm 2.0.12-8
startdde 5.5.0.7-1 (deepin)
```

**Comment by balibebas** [comment]
I'm running DDE on Arch and had some problems with window management after a recent update. Here's how I fixed a number of window management problems on my Arch Linux installation: https://forum.manjaro.org/t/various-deepin-desktop-and-kwin-related-issues-window-effects-wallpapers-etc/152061/4

**Comment by awesomepandata** [comment]
> I'm running DDE on Arch and had some problems with window management after a recent update. Here's how I fixed a number of window management problems on my Arch Linux installation: https://forum.manjaro.org/t/various-deepin-desktop-and-kwin-related-issues-window-effects-wallpapers-etc/152061/4


If I delete the kwinrc file, I get no compositor, but it's a good workaround or just disable in control panel.

**Comment by Saduff** [comment]
Deleting kwinrc seems to have fixed the second maximized window problem, i.e. the right side of the window is now clickable. However, the minimize button issue remains as in it only works once.

**Comment by balibebas** [comment]
> After selecting a custom application style theme from KDE settings, the maximized window problem appears again.

Why are using KDE settings on a Deepin desktop? Deepin has it's own settings manager.

**Comment by balibebas** [comment]
> After selecting a custom application style theme from KDE settings, the maximized window problem appears again.

Why are using KDE settings on a Deepin desktop? Deepin has its own settings manager.

**Comment by xd003** [comment]
can confirm facing this exact same issue on Endeavour OS ( arch based rolling distro )
i hope this issue gets fixed on a priority basis as its very critical and affects proper usage 

Whenever i open any app for first time , i am able to minimize it 
But if i open that app again from dock and try to minimize it for second time, it doesn't gets minimized

**Comment by luosoy** [comment]
This bug is hidden in the lib dtkwidget（https://github.com/linuxdeepin/dtkwidget/releases/tag/5.2.2.2），But I can't find out which line of code caused it

**Comment by luosoy** [comment]
I create project with only two lib Qt5Widgets  DtkWidget and use only two class DApplication DMainWindow. can recreate the bug

**Comment by luosoy** [comment]
Maybe Dtkwidget is not compatible with qt5.15.0

**Comment by luosoy** [comment]
there are something bug with QT5 when use showMinimized

**Comment by luosoy** [comment]
# Maintainer: Felix Yan <felixonmars@archlinux.org>
# Contributor: Josip Ponjavic <josipponjavic at gmail dot com>
# Contributor: Xu Fasheng <fasheng.xu[AT]gmail.com>

pkgname=dtkwidget
pkgver=5.2.2.3
pkgrel=1
pkgdesc='Deepin graphical user interface library'
arch=('x86_64')
url="https://github.com/linuxdeepin/dtkwidget"
license=('LGPL3')
depends=('deepin-qt-dbus-factory' 'dtkcore' 'dtkgui' 'librsvg' 'qt5-multimedia' 'qt5-svg'
         'qt5-x11extras' 'startup-notification')
makedepends=('qt5-tools')
replaces=('deepin-tool-kit')
conflicts=('deepin-tool-kit<0.3.4')
source=("$pkgname-$pkgver.tar.gz::https://github.com/linuxdeepin/dtkwidget/archive/$pkgver.tar.gz")
sha512sums=('62e6b667283cd7e1ddc8653db16561e68911c21b9085241c4e0bb16f42a3f2ba2f97f0ef76d3666697dc11495267f4f2cf67746b4cd2f08af2e71e22df8674ce')

prepare() {
  cd dtkwidget-$pkgver
  sed -i '/#include <QPainter>/a #include <QPainterPath>' src/util/dwidgetutil.cpp
  sed -i '/targetWindow()->showMinimized();/i if (targetWindow()->isMinimized()) {if (targetWindow()->isMaximized()) {targetWindow()->showMaximized();} else {targetWindow()->showNormal();}}' src/widgets/dtitlebar.cpp
}

build() {
  cd dtkwidget-$pkgver
  qmake-qt5 PREFIX=/usr
  make
}

package() {
  cd dtkwidget-$pkgver
  make INSTALL_ROOT="$pkgdir" install
}

把上面的代码复制到PKGBUILD文件中执行makepkg进行编译，用sudo pacman -U 重新安装dtkwidget 可以解决这个问题，但是不知道会不会引起其他问题

**Comment by Saduff** [comment]
Thanks @luosoy. Tried the PKGBUILD, had to remove the `sed -i '/#include /a #include ' src/util/dwidgetutil.cpp` or the package wouldn't compile.

This modified version of `dtkwidget` does fix the minimize button. However, the second issue with the maximized window remains. There's also some other weird behavior. To reproduce:

1. Open a Deepin app
2. Click the maximize button
3. Click the minimize button
4. Bring the app back into focus
5. Use a keyboard shortcut (Win+↓) to unmaximize the window
6. Click the minimize button
7. Bring the app back into focus

The app comes back as maximized even though the last state was not maximized.

**Comment by Sophon96** [comment]
I am also having the same minimize button issue running Deepin on Arch Linux, but turning off "Window Effect" under "Personalization" in settings seems to fix it, albeit not rendering shadows.

**Comment by haonanq666** [comment]
Just adding in to this, I am running latest versions of deepin, deepin-extra, deepin-kwin. Issue still persists, minimize button works only the first time for dde apps. Other programs such as chromium work as expected. Compiling the custom PKGBUILD works but breaks dde-file-manager (and I believe dde-control-center broke too, did not test extensively). 

尝试了 @luosoy 大佬的方法，无法编译。依照@Saduff 的方法删除 ```sed -i '/#include /a #include ' src/util/dwidgetutil.cpp```后可安装。安装后最小化好使了，但是dde-file-manager报错 ```symbol lookup error: /usr/lib/libdde-file-manager.so.1: undefined symbol: _ZN3Dtk6Widget7DDialog11eventFilterEP7QObjectP6QEvent```并无法打开。

**Comment by Saduff** [comment]
Yes, problem still exists with current latest versions.

> I am also having the same minimize button issue running Deepin on Arch Linux, but turning off "Window Effect" under "Personalization" in settings seems to fix it, albeit not rendering shadows.

Yeah, same here, but turning that off means there's no compositor.

> P.S. The right side of the window was always clickable for me, was unable to replicate this part of the bug.

I found that this is caused by selecting a custom application style theme from KDE settings. Deleting `~/.kwinrc` fixed it, which resets all the KWin settings to Deepin defaults. Probably not supposed to fiddle much with the KDE settings when using Deepin, but the main reason I did that before was because Deepin didn't seem to have a dark themed application title bar even when the dark theme was selected. However, that changed at some point and a dark title bar exists now, so I haven't changed to a custom theme anymore to avoid that issue.
