### ISSUE TITLE
Network password dialog doesn't show up on Arch through the applet on dde-dock

### ISSUE THREAD

**Issue by gustavodlima** [linuxdeepin/developer-center#199]
When I try to connect to a new network through the applet on dde-dock, the password dialog doesn't shows up and it never connects. I have to use `nmtui` to connect to a network. Same occurs when I try to connect using Control Center, it just doesn't asks me about the password and literally take forever to not connect.

Packages: `networkmanager-1.6.2-3`, ` deepin-dock-4.1.7-1`, and everything else updated as well.

**Comment by pablomancera** [comment]
I have just the same problem

**Comment by pablomancera** [comment]
Fixed in `deepin-dock 4.1.7-2`

**Comment by oberon2007** [comment]
Not fixed for me. it's the same old issue as we had already.
When I am trying to a new network that I haven't used before I need to use **nmtui** once and enter the password there. From now on the network module of deepin is able to connect to the network.

**Comment by Acris** [comment]
Same problem for me.

**Comment by funilrys** [comment]
It's really random now @oberon2007 It's working over 2/3 computer by me ...
