### ISSUE TITLE
[Archlinux] Graphic worries after fresh install

### ISSUE THREAD

**Issue by beauraF** [linuxdeepin/developer-center#200]
Hi,

After a fresh Archlinux + Deepin install, I meet this big graphic worries :

![captureecrandeepin20170316134347](https://cloud.githubusercontent.com/assets/12185788/24010552/9e130f08-0a4e-11e7-927f-1df4069f8a16.png)

My graphic driver are up to date :
`extra/xf86-video-ati 1:7.8.99.r38.g9035b6ab-1 (xorg-drivers) [installé]
    X.org ati video driver
`

And I use the last version of `deepin-clutter` (As recommended here : https://github.com/linuxdeepin/developer-center/issues/195) :
`deepin-clutter-1.26.2-1 est à jour`

Thank you in advance for your help.

**Comment by gustavodlima** [comment]
How did you installed your graphics driver? Have you followed the guide provided by Arch Wiki?

**Comment by sonald** [comment]
I guess this is a driver problem.  check if dmesg has any drm errors or warnings.

**Comment by beauraF** [comment]
I installed my archlinux with ArchEverywhere which detected my hardware and installed the right drivers.
I checked it is the right driver that is installed : `xf86-video-ati`

> dmesg | grep drm
> [    9.608353] [drm] Initialized
> [    9.783559] [drm] radeon kernel modesetting enabled.
> [   10.114586] fb: switching to radeondrmfb from VESA VGA
> [   10.128390] [drm] initializing kernel modesetting (TURKS 0x1002:0x6841 0x103C:0x17A9 0x00).
> [   10.128399] [drm] register mmio base: 0xD4300000
> [   10.128399] [drm] register mmio size: 131072
> [   10.128528] [drm] Detected VRAM RAM=1024M, BAR=256M
> [   10.128528] [drm] RAM width 64bits DDR
> [   10.128581] [drm] radeon: 1024M of VRAM memory ready
> [   10.128581] [drm] radeon: 1024M of GTT memory ready.
> [   10.128586] [drm] Loading TURKS Microcode
> [   10.701930] [drm] Internal thermal controller with fan control
> [   10.705300] [drm] radeon: dpm initialized
> [   10.733943] [drm] GART: num cpu pages 262144, num gpu pages 262144
> [   10.734876] [drm] enabling PCIE gen 2 link speeds, disable with radeon.pcie_gen2=0
> [   10.736974] [drm] PCIE GART of 1024M enabled (table at 0x0000000000162000).
> [   10.737481] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
> [   10.737481] [drm] Driver supports precise vblank timestamp query.
> [   10.737538] [drm] radeon: irq initialized.
> [   10.753927] [drm] ring test on 0 succeeded in 1 usecs
> [   10.753934] [drm] ring test on 3 succeeded in 4 usecs
> [   10.931334] [drm] ring test on 5 succeeded in 2 usecs
> [   10.931340] [drm] UVD initialized successfully.
> [   10.931536] [drm] ib test on ring 0 succeeded in 0 usecs
> [   10.931563] [drm] ib test on ring 3 succeeded in 0 usecs
> [   11.595679] [drm] ib test on ring 5 succeeded
> [   11.662288] [drm] radeon atom DIG backlight initialized
> [   11.662294] [drm] Radeon Display Connectors
> [   11.662296] [drm] Connector 0:
> [   11.662297] [drm]   LVDS-1
> [   11.662299] [drm]   DDC: 0x6430 0x6430 0x6434 0x6434 0x6438 0x6438 0x643c 0x643c
> [   11.662300] [drm]   Encoders:
> [   11.662301] [drm]     LCD1: INTERNAL_UNIPHY
> [   11.662302] [drm] Connector 1:
> [   11.662302] [drm]   DP-1
> [   11.662303] [drm]   HPD1
> [   11.662305] [drm]   DDC: 0x6470 0x6470 0x6474 0x6474 0x6478 0x6478 0x647c 0x647c
> [   11.662305] [drm]   Encoders:
> [   11.662306] [drm]     DFP1: INTERNAL_UNIPHY1
> [   11.662307] [drm] Connector 2:
> [   11.662308] [drm]   DP-2
> [   11.662308] [drm]   HPD2
> [   11.662310] [drm]   DDC: 0x6440 0x6440 0x6444 0x6444 0x6448 0x6448 0x644c 0x644c
> [   11.662310] [drm]   Encoders:
> [   11.662311] [drm]     DFP2: INTERNAL_UNIPHY1
> [   11.662311] [drm] Connector 3:
> [   11.662312] [drm]   DP-3
> [   11.662313] [drm]   HPD3
> [   11.662314] [drm]   DDC: 0x6450 0x6450 0x6454 0x6454 0x6458 0x6458 0x645c 0x645c
> [   11.662315] [drm]   Encoders:
> [   11.662315] [drm]     DFP3: INTERNAL_UNIPHY2
> [   11.662316] [drm] Connector 4:
> [   11.662317] [drm]   VGA-1
> [   11.662318] [drm]   DDC: 0x64d8 0x64d8 0x64dc 0x64dc 0x64e0 0x64e0 0x64e4 0x64e4
> [   11.662319] [drm]   Encoders:
> [   11.662320] [drm]     CRT1: INTERNAL_KLDSCP_DAC1
> [   12.174225] [drm] fb mappable at 0xC0363000
> [   12.174228] [drm] vram apper at 0xC0000000
> [   12.174229] [drm] size 8294400
> [   12.174230] [drm] fb depth is 24
> [   12.174231] [drm]    pitch is 7680
> [   12.174430] fbcon: radeondrmfb (fb0) is primary device
> [   12.660252] radeon 0000:01:00.0: fb0: radeondrmfb frame buffer device
> [   12.683291] [drm] Initialized radeon 2.49.0 20080528 for 0000:01:00.0 on minor 0

> 
> startdde
> org.freedesktop.DBus.Error.NoReply:Message recipient disconnected from message bus without replying
> <info> sound_effect.go:21: PlaySystemSound EventLogin
> <info> sound_effect.go:26: PlaySystemSound EventLogin done
> <error> xsettings.go:154: Install dbus session failed: name com.deepin.SessionManager already taken
>   ->  main.go:50
>   ->  proc.go:185
>   ->  asm_amd64.s:2197
> <error> session.go:210: Install Session DBus Failed: name com.deepin.SessionManager already taken
>   ->  main.go:54
>   ->  proc.go:185
>   ->  asm_amd64.s:2197
> <error> display.go:15: Install session bus failed: name com.deepin.daemon.Display already taken
>   ->  asm_amd64.s:2197

**Comment by sonald** [comment]
@beauraF try run deepin-wm in a terminal:
1. pkill deepin-wm-switcher
2. export MESA_DEBUG=1
    export LIBGL_DEBUG=1
    export COGL_DEBUG=1
    deepin-wm --replace &
then, you can see if there are any errors show up in the terminal.

**Comment by beauraF** [comment]
> libGL: Can't open configuration file /home/beauraf/.drirc: Aucun fichier ou dossier de ce type.
> libGL: Can't open configuration file /home/beauraf/.drirc: Aucun fichier ou dossier de ce type.
> libGL: Can't open configuration file /home/beauraf/.drirc: Aucun fichier ou dossier de ce type.
> 
> [1]  + 1882 done       deepin-wm --replace

**Comment by beauraF** [comment]
Sorry, miss click.

**Comment by gustavodlima** [comment]
@beauraF Just to make sure, try `$ sudo chmod 777 /dev/dri/card0`, and then `$ sudo usermod -aG video $(users)`.

**Comment by beauraF** [comment]
@gustavodlima nop :(

**Comment by sonald** [comment]
@beauraF what is the version of deepin-mutter ? make sure it is at least 3.20.12

**Comment by beauraF** [comment]
All of my packages were up to date.
Unfortunately, I'm switching to another DE. I could not wait any longer.

Other people have the problem, as you can see on the issue I referenced. I hope they can answer your questions.

Feel free to close this issue if you feel it is no longer needed. I leave it open.

Thank you for your assistance and your time.

**Comment by pablomancera** [comment]
I have the same problem, with the dock, the rigth panel and the notifications, I have nothing related to this problem to update

![deepinscreenshot20170318145027](https://cloud.githubusercontent.com/assets/26395881/24075485/7f851566-0bea-11e7-8f12-8e2ba6459511.png)

**Comment by sonald** [comment]
@pablomancera this should be fixed by deepin-clutter.....

**Comment by beauraF** [comment]
`deepin-clutter` did not fix it for me either. Even on a fresh install.

**Comment by pablomancera** [comment]
Yes, it dont have relation with dolphin-clutter, i've updated the package before taking the screenshot

**Comment by sonald** [comment]
as far as I can tell, this happens just on some of AMD cards with radeon driver. I need some time to figure it out.

**Comment by pablomancera** [comment]
I'm using a Intel HD graphics card
![deepinscreenshot20170320012410](https://cloud.githubusercontent.com/assets/26395881/24090200/01848fc0-0d0c-11e7-9929-aa8f97562e30.png)

**Comment by pablomancera** [comment]
I'm using a Intel HD Graphics card

**Comment by sonald** [comment]
Which means this is a driver related issue. what xorg driver did you use ? some intel cards do not perform well with modesettings driver. maybe you can try with intel driver or just change accelaration method.

**Comment by pablomancera** [comment]
I'm using `xf86-video-intel 1:2.99.917+767+g7e9e92c8-1` and `mesa 17.0.1-2`

**Comment by wilkmaia** [comment]
I have a similar issue when I have a second display plugged in through HDMI.

Sometimes (not always) **when the window on the second display isn't focused** its borders flash (somehow like the other problems discussed). Focusing on the window promptly stops the flashing.

It **only** happens on a second monitor through HDMI (my laptop doesn't have a VGA output so I can't say anything about it).

I have an NVIDIA card with Optimus. I use the Bumblebee service to control the graphics driver.

**Comment by gustavodlima** [comment]
Whoa... I just restarted the laptop after updated the system hours ago and now:

![deepinscreenshot20170327100731](https://cloud.githubusercontent.com/assets/14314943/24358537/d6658b06-12d7-11e7-9d87-c89a2fa05097.png)

![deepinscreenshot20170327100738](https://cloud.githubusercontent.com/assets/14314943/24358545/db9880e2-12d7-11e7-800a-d411bd9574e2.png)

Oh boy... :(

**Comment by S6066** [comment]
Hello, installed arch linux with architect, installed my graphics driver with `sudo pacman -Syu xf86-video-amdgpu` (I have an AMD RX 460) and I have the same kind of issues. No issue with Gnome though.
I don't want to stay with Gnome, I prefer deepin but I can't use it with this issues...

**Comment by funilrys** [comment]
strange cause I use amdgpu/ati too but no problem since almost 1 year

**Comment by sonald** [comment]
@gustavodlima which means upgrade make things broken. can you identify which packages gets updates  d last time ?

**Comment by funilrys** [comment]
@gustavodlima As we said in another issue it's really random cause I don't have such issue :-1:

**Comment by gustavodlima** [comment]
@sonald Sadly I'm not using Deepin right now. I'll give it a try later and keep supporting the translating project and "spreading the message" from such a good project. I expect so much of it but as @funilrys said, it's just random issues and I opted to keep as my secondary DE. I'll try to find what packages I've updated but I really don't remember right now. What I remember is that was just Deepin related packages. 

And reinforcing what @funilrys said, he doesn't have such issue and few time ago I didn't have it either. As a developer, I know that upgrades can break things, but it's just that I can't use such a beautiful DE with random rendering problems. It breaks all the original purpose of using it.

And not less important, thank you guys! :)

**Comment by sonald** [comment]
@gustavodlima Ok,I understand. The rendering problem should be the driver issue, so what yu encountered confused me and I just want to be sure. We'll keep improving DDE and keep you guys updated with progress.

**Comment by sonald** [comment]
@beauraF @gustavodlima @pablomancera We just fixed a rendering error caused by locale (any locale other than en_US may has this issue. the fix resides in deepin-mutter 3.20.15, arch should ship with it soon. you may try it.

**Comment by beauraF** [comment]
Hi @sonald. I'm glad to hear that. Unfortunately I do not currently use DDE. I will try as soon as possible and keep you informed.

**Comment by gustavodlima** [comment]
@sonald What a great news! In the situation, I've updated some packages hours ago as I mentioned, but the real reason I've restarted was 'cause I've set a new locale variable to fix #212.

**Comment by pablomancera** [comment]
@sonald Yeah, is working now, thanks
![deepinscreenshot20170331220224](https://cloud.githubusercontent.com/assets/26395881/24574799/d39d78f0-165d-11e7-8d42-d2d6dce0963c.png)

**Comment by sonald** [comment]
I'm glad it works, looks great :)
