### ISSUE TITLE
[Arch Linux] Black screen and cursor only after session login

### ISSUE THREAD

**Issue by bmentink** [linuxdeepin/developer-center#213]
Hi,

After updating a few weeks ago, I can no longer use Deepin Desktop on my work PC, as after logging in on the session manager, all I get is a black screen with a cursor. Nothing else works. I cannot get to any TTY also. My only option was to break into grub, boot into a console only, and install XFCE to get my computer back.

Very frustrating, as I prefer Deepin. I have updated deepin every few days to see if there is a fix.

If I start "startdde" by putting "exec startdde" in ~/.xinitrc (instead of via session in lightdm), then the same black screen results.

This black screen issue only seems to be on my work PC which has NVIDIA graphics ... my home laptop with INTEL graphics works fine on the latest updates.

**Comment by funilrys** [comment]
cc @oberon2007 :wink: :stuck_out_tongue_closed_eyes: :smile_cat:

**Comment by oberon2007** [comment]
This sounds very much as it is not an issue of Deepin but with your NVIDIA driver!

**Comment by funilrys** [comment]
So true @oberon2007 :wink: @bmentink [which driver ](https://wiki.archlinux.org/index.php/NVIDIA)do you use ?

**Comment by bmentink** [comment]
Hi, I am using the x86-video-nouveau driver. If it is the driver, then why does XFCE work fine ...
and Deepin used to work fine as well ..

**Comment by bmentink** [comment]
A further update: I installed the nvidia driver for my card from Arch repo (nvidia-340xx). Rebooted and made sure XFCE ran with new driver. That was fine. Booted up a Deepin Session and initially I had the same black screen.

I did a Ctrl-Alt-F1/F7 cycle and then one of my Opera Browser Windows showed up and I could drag it to the right 1/2 of the screen fine .... inside the window is weird with what looks t like multiple versions of itself. Nothing else works, no panel, no wallpaper, no apps ....

So, it does not seem to be the driver, I repeat, it works with XFCE and lsmod shows the new module loaded.

**Comment by hualet** [comment]
@jouyouyun @Iceyer I guess this one is not brightness related, XFCE works anyway.

**Comment by bmentink** [comment]
What do you mean brightness related? Has there been an issue with that?

**Comment by felixonmars** [comment]
@bmentink You might want to check if your OpenGL stack is working correctly. Try following commands in a TTY:

```
DISPLAY=:0 glxgears
DISPLAY=:0 glxinfo | grep "direct rendering"
```

You should see rotating gears window in the desktop and "direct rendering: Yes". Otherwise, you should fix your OpenGL stack first.

**Comment by bmentink** [comment]
glxgears works just fine, and "direct rendering" is enabled ..

**Comment by felixonmars** [comment]
OK.. You might try to kill and start the following components in a terminal, and see if they exits with an error:

```
killall dde-session-initializer; /usr/lib/deepin-daemon/dde-session-initializer -v
killall dde-session-daemon; /usr/lib/deepin-daemon/dde-session-daemon -v
sudo killall dde-system-daemon; sudo /usr/lib/deepin-daemon/dde-system-daemon -v
```

**Comment by bmentink** [comment]
Hmmm, As I already stated in my OP, I can't get to a TTY, so doing that won't work ..

**Comment by felixonmars** [comment]
That's unfortunate. Maybe a symlink to `/usr/share/applications/deepin-terminal.desktop` in `~/.config/autostart/` would bring you with a terminal window on startup :)

**Comment by bmentink** [comment]
Ok, will do that when I am back at work.. cheers

**Comment by TheInitializer** [comment]
I believe I am the "other that has the same issue" :p

A few additional details:
 - I'm starting the DE from GDM
 - Discord starts up normally as I have it set to open on startup
 - Hot corners appear to work, and the startup sound plays, but I can't right click on the completely blank desktop.

**Comment by TheInitializer** [comment]
As well (on mobile so can't edit):
 - Window animations and snapping work fine
 - Using Intel HD graphics card, I can't remember what driver I ended up using

Will try setting terminal to start up on login.

**Comment by bmentink** [comment]
I tried setting auto-start terminal, did not show ...

**Comment by TheInitializer** [comment]
Auto terminal worked for me. Was able to start up firefox and type this.

**Comment by TheInitializer** [comment]
```
[david@davidsarch ~]$ sudo killall dde-system-daemon; sudo /usr/lib/deepin-daemon/dde-system-daemon -v
[sudo] password for david: 
<warning> main.go:32: There already has an dde daemon running.
[david@davidsarch ~]$ 
```

**Comment by TheInitializer** [comment]
Ooh, I might have found my problem.

When I try to start `dde-dock` from the terminal, it gives me this error: 

```
[david@davidsarch ~]$ dde-dock
dde-dock: /usr/lib/libQt5Core.so.5: version `Qt_5.8' not found (required by dde-dock)
dde-dock: /usr/lib/libQt5Core.so.5: version `Qt_5.8' not found (required by /usr/lib/libdtkwidget.so.1)
dde-dock: /usr/lib/libQt5Core.so.5: version `Qt_5.8' not found (required by /usr/lib/libdtkbase.so.1)
dde-dock: /usr/lib/libQt5Core.so.5: version `Qt_5.8' not found (required by /usr/lib/libdtkutil.so.1)
dde-dock: /usr/lib/libQt5Core.so.5: version `Qt_5.8' not found (required by /usr/lib/libdtksettingsview.so.1)
dde-dock: /usr/lib/libQt5Core.so.5: version `Qt_5.8' not found (required by /usr/lib/libdtksettings.so.1)
```

Do I just need to update Qt then?

**Comment by bmentink** [comment]
Latest Arch update has qt5.8, which is what I am running ....

**Comment by TheInitializer** [comment]
Running a `pacman -Syu`, let's see if that helps.

**Comment by bmentink** [comment]
We need some help from developers here to solve this. Mine still does not work.

**Comment by hualet** [comment]
Is startdde running correctly after session login ?
If the anwser is yes, try "qdbus --literal com.deepin.daemon.Display /com/deepin/daemon/Display com.deepin.daemon.Display.Reset" in your TTY, and don't forget to export the DISPLAY environment virable.

**Comment by bmentink** [comment]
I don't know, I have no way of telling as I have stated  several times, I cannot get a TTY, I am blind.

**Comment by funilrys** [comment]
@bmentink can you access single mode then ?

**Comment by bmentink** [comment]
Don't you guys read my original post? I said the only way I could get to a console was to break into grub and run up a shell. How is that going to help. I already said that doing a startx (startdde) did the same black screen thing ..

**Comment by jouyouyun** [comment]
@bmentink Can you login with xfce4? If ok, please paste the output of `gsettings get com.deepin.dde.display brightness`
If the value was 0, please exec `gsettings reset com.deepin.dde.display brightness`, then retry login with startdde, thanks!

**Comment by bmentink** [comment]
Yes, of course I can login with XFCE (again I said as much in my original post) .. sigh!
I will do what you ask tomorrow when I can get to my work machine again ..

**Comment by funilrys** [comment]
@bmentink 
In between some days ago I had the problem with black wallpapers 
I backuped and rmed `~/.config/dde-*` && `~/.config/Deepin/*` && `~/.config/deepin/*`  && `~/.cache/dde-*` && `~/.cache/Deepin/*` && `~/.cache/dde-*` `~/.cache/deepin/*` (I'm kinda crazy :stuck_out_tongue_closed_eyes: but that was the only thing I had in mind in the time :smile_cat:)  then rebooted and the problem was gone ...

**Comment by bmentink** [comment]
@jouyouyun 
output is: 
> {"DP-1":0.02,"DP-2":0.02}'

**Comment by bmentink** [comment]
@funilrys 
I had already tried that, but thanks. Did not help for me ..
Any other suggestions anyone?

**Comment by jouyouyun** [comment]
@bmentink exec `gsettings reset com.deepin.dde.display brightness` under xfce4 will fix this problem.

**Comment by teoten** [comment]
It does the trick for me @jouyouyun 

I did it from cinnamon :)

**Comment by bmentink** [comment]
Also does the trick for me .... many thanks. :+1:

**Comment by funilrys** [comment]
@bmentink, you can close this issue then 😉

**Comment by bmentink** [comment]
Seems this is fixed then ....

**Comment by RickStanley** [comment]
Unfortunatetly, the issue persists for me.
I tried `gsettings reset com.deepin.dde.display brightness` and got:
```
(process:9616): dconf-WARNING **: failed to commit changes to dconf: Error spawning 
command line `dbus-launch --autolaunch=aaa5bb6eaa7cd50f2af1f10000000004 --binary-syntax 
--close-stderr': Child process exited with code 1
```
; then I tried `sudo -u [my-username] dbus-launch gsettings reset com.deepin.dde.display brightness`, no errors returned, from liveusb, and also as arch-chroot.

**Comment by smdahmed** [comment]
@jouyouyun - Your tip of running gsettings reset com.deepin.dde.display brightness did the job for me. For the benefit of other users who are running Ubuntu + have installed DDE and hit this post, I face this issue when the power cable to the laptop is disconnected and connected back immediately when moving while seated. Any attempts to relogin will not solve the dark screen issue. So I relogin into the Ubuntu desktop environment and then run this command.

Apart from this, I did also remove the dde folder under .cache/deepin. I dont think this has much play into the fix but listed here as I did these 2 steps.
