### ISSUE TITLE
dde-dock 4.1.8 paints a wide black bar on startup

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#218]
After upgrading to latest dde-dock 4.1.8, a wide black bar will be shown on startup, before the actual dock appears. This was not seen on earlier versions.

![2017-04-01-124200-86b0e6](https://cloud.githubusercontent.com/assets/1006477/24575567/6aa5fe42-16dc-11e7-9176-879220503b46.png)

**Comment by hualet** [comment]
@sbwtw that's what I saw everytime I reboot my computer :sweat:

**Comment by sbwtw** [comment]
upload your  ~/.cache/deepin/dde-dock/dde-dock.log

**Comment by felixonmars** [comment]
[dde-dock.zip](https://github.com/linuxdeepin/developer-center/files/887412/dde-dock.zip)

**Comment by sbwtw** [comment]
@dragondjf is working on this problem.

**Comment by funilrys** [comment]
Same here 

![deepinscreenshot20170401161623](https://cloud.githubusercontent.com/assets/14127285/24579510/85be51a0-16f7-11e7-80b4-e0ac70af4cc4.png)

**Comment by hualet** [comment]
This problem should be fixed by upgrading disk-mount plugin of Dock.

**Comment by felixonmars** [comment]
We have latest dde-file-manager 4.1.3 packaged, so I guess it's still not fixed?

**Comment by hualet** [comment]
@felixonmars what if you drop the disk-mount plugin ? do you still get the black Dock ?

**Comment by felixonmars** [comment]
Yes, I still get it. Running the following command can reproduce the problem ~50% of the time:

```
killall dde-session-daemon dde-dock; dde-dock &
```

And when the black Dock shows, the log is at `init plugin:  "sound"`. There are also retries for the power plugin around that time:
```
[shutdownplugin.cpp   ShutdownPlugin::delayLoader         196] load power failed, wait and retry 2
```

**Comment by hualet** [comment]
So we may need other workable ways to tackle this problem. @sbwtw

**Comment by felixonmars** [comment]
Update: I can no longer reproduce the problem when the sound plugin is removed from my disk.

**Comment by hualet** [comment]
Ah, god ! Every single plugin of dde-dock seems to broken recently, what's going on 😭

**Comment by felixonmars** [comment]
Update 2: Sorry I was too fast. The problem still persists, and I have a better way to reproduce it (100%):
```
kwin_x11 --replace
```
(wm-switcher will switch back to deepin-wm, though.)

It's also present even when I removed everything under /usr/lib/dde-dock/plugins/.

It no longer happens immediately after downgrading to 4.0.7, even with all plugins loaded. So I guess the problem is inside dde-dock itself.

**Comment by hualet** [comment]
I'm not sure if they're the same thing. 
How long does it take before Dock looks normal again?

**Comment by felixonmars** [comment]
2~5s normally.

**Comment by hualet** [comment]
Then it doesn't sound like a plugin blocking thing.
Maybe this is introduced by adding shadows for Dock ? @sbwtw @zccrs
