### ISSUE TITLE
wifi password bug

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/developer-center#246]
Since I have no option available to reopen [this bug report](https://github.com/linuxdeepin/developer-center/issues/199), I'm creating a new one. It is still (or again, I'm not completely sure) present for me and it's a real problem.
In order to reproduce this you need to try to connect to a password protected wifi network **for the first time**, so, when you have never entered the password before!
Now when I click on the network icon in the dock and select the network I will see a spinning circle for a very long time, but a dialog for entering the password will never show up.
When I open the control center and open the settings for the same network, I have a field for the password where it says "required". Entering the password there doesn't change anything and when I open the tab again later, the field will be empty again.

**Comment by oberon2007** [comment]
I just found out that after a reboot suddenly I am being connected to the wifi. So somehow the password I had entered in the control center was remembered. So from now on it will likely not have any problem to connect to the same network.
Still this is a bug and I will have the same problem with another new network... :stuck_out_tongue_winking_eye:  Something is not right here.

**Comment by funilrys** [comment]
A new random issue @oberon2007 :stuck_out_tongue_winking_eye: But you're right it's not good to have such bug .... Is it a manjaro issue ?

**Comment by oberon2007** [comment]
No, it's not random. I can reproduce it every time. No other Manjaro DE has this problem. So I would say it's a deepin issue. Are you running Arch? I read that you noticed the issue, too, right?

**Comment by funilrys** [comment]
@oberon2007 I'm with arch and I do not have this problem anymore over 2 fresh installation ...

**Comment by funilrys** [comment]
Okay, so I cleared all my network for simulation @oberon2007.

Result : 
Fresh install (since 4 day) ==> white deepin dialog appear but password is not saved after log out/in
1 year install ==> white deepin dialog appear password is saved ... It's really weird

**Comment by jsfaint** [comment]
I have same issue on ArchLinux, it appeared since last month. after an upgrade of deepin desktop
I tried to switch to another desktop like xfce4, there is no this issue.

**Comment by oberon2007** [comment]
It seems the Deepin connection widget to work properly needs 
```
[device]
wifi.scan-rand-mac-address=no
```
in **/etc/NetworkManager/NetworkManager.conf**.
Don't know why, but that seems to work.

**Comment by jsfaint** [comment]
@oberon2007 This workaround works for me, thanks!

**Comment by hualet** [comment]
@jouyouyun

**Comment by alexandre1985** [comment]
this also works for me

**Comment by icp1994** [comment]
Had the same problem in new Manjaro Deepin installation today and workaround fixed it!

**Comment by petoem** [comment]
Works for me on archlinux, thanks!

**Comment by jouyouyun** [comment]
Solved by edit the file ` /etc/NetworkManager/NetworkManager.conf`.

**Comment by amiralisalimi** [comment]
@jouyouyun  This solution did solve my problem on networks which I had connected before, and saved password for them. But for new networks, the bug is not solved. I'm pretty sure I gave the password correct, but after a while, It gives `wrong password` error.

**Comment by jouyouyun** [comment]
> @jouyouyun This solution did solve my problem on networks which I had connected before, and saved password for them. But for new networks, the bug is not solved. I'm pretty sure I gave the password correct, but after a while, It gives `wrong password` error.

Please upload the log by the command `sudo journalctl -b 0 > /tmp/sys.log` after this bug reproduce and the WIFI SSID name, thanks!

**Comment by dellitsni** [comment]
I'm facing the same issue on a new install of Arch + Deepin. The chipset is Realtek RTL8153. 
It's worked flawlessly a few times, but almost always (every single time I've tried over the last 2 weeks), it bugs out and goes nuts. I've resorted to connecting via the CLI and some fancy aliases, but whenever I stumble into rare setups (MSCHAPV2 most recently), I'm pretty much fucked. 

Notable excerpts from the log being `daemon/network[1008]: manager_device.go:395: failed to get interface info: route ip+net: no such network interface`, and `kwin_x11[962]: file:///usr/share/kwin/tabbox/chameleon/contents/ui/main.qml:273:33: Unable to assign QUuid to int`
