### ISSUE TITLE
BUG - Can't manually change mirror 

### ISSUE THREAD

**Issue by raspin0** [linuxdeepin/developer-center#2755]
https://user-images.githubusercontent.com/39202451/121435571-68ba4700-c97f-11eb-92cf-1ed1b3752dfc.mp4

**Comment by BLumia** [comment]
Sorry for the super late response since we did not look into issues that were created outside the developer-center repo.

I cannot reproduce this issue on `deepin v20.4` with `dde-control-center 5.5.11.5-1`, so hopefully it's already been resolved in previous updates.

Since it cannot be reproduced, I'll close this issue for now. If you can still reproduce this issue on the most recent release you can get, please consider creating another issue with the necessary detailed information so we can look into it. Thanks!

**Comment by raspin0** [comment]
> Sorry for the super late response since we did not look into issues that were created outside the developer-center repo.
> 
> I cannot reproduce this issue on `deepin v20.4` with `dde-control-center 5.5.11.5-1`, so hopefully it's already been resolved in previous updates.
> 
> Since it cannot be reproduced, I'll close this issue for now. If you can still reproduce this issue on the most recent release you can get, please consider creating another issue with the necessary detailed information so we can look into it. Thanks!

It still reproduces. What detailed information you want me to provide?

**Comment by BLumia** [comment]
Oh, I double-checked this issue and now I'm able to reproduce it under `deepin v20.4` with `dde-control-center 5.5.11.5-1`. Since the information on this issue is still valid, I'll reopen this one.

**Comment by SuperEffie** [comment]
Thank for your feedback.This issue has been confirmed to exist in the deepin v20.5 too. It has been reported to the developer,and we will inform you after the fix.

**Comment by SuperEffie** [comment]
Thank you very much for submitting the issue. As version V20.9 and later will no longer receive updates, we will continue to monitor this issue in deepin V23. If you are able to use V23 in the future and encounter any problems, please feel free to submit them. We will close this issue for now and keep an internal record. Thank you again for your attention.
