### ISSUE TITLE
[Dock] Dock uses 100% of CPU core and creates many processes

### ISSUE THREAD

**Issue by avently** [linuxdeepin/developer-center#363]
1. Dde-dock uses 100% of CPU core. I don't know why and how to find what is causing it, I'm making killall dde-dock then Dock restarts with 100% of CPU.
![deepinscreenshot_20170916231104](https://user-images.githubusercontent.com/7953703/30515627-88aca0e4-9b34-11e7-8ef4-43e120aeeb20.png)
2. Sometimes after log in i have many dde-dock instances. Then i can get even more insances if i repeat log out & log in to system.

Can you fix it?

**Comment by hualet** [comment]
Your OS ? and version ?
Also please attach the log file of dde-dock which can be found at ~/.cache/deepin/dde-dock/dde-dock.log :)

**Comment by avently** [comment]
Seems like multiple instances of dde-dock exist because i'm switching from one Gnome shell to Deepin. 
Here is a log when dock uses 100% and multiple instanses started.
[dde-dock.txt](https://github.com/linuxdeepin/developer-center/files/1310286/dde-dock.txt)

**Comment by hualet** [comment]
Is Dock showing ?

**Comment by avently** [comment]
@hualet yes

**Comment by hualet** [comment]
What if you go DDE session directly ?

**Comment by avently** [comment]
@hualet what do you mean by "directly"?
Here is what I'm doing:
Going to Gnome Xorg
Ctrl + Alt + Backspace
Logging in Deepin
100% cpu
Ctrl + Alt + Backspace
Logging in Feeling
New dde-dock process added

**Comment by avently** [comment]
Also /usr/bin/dde-file-manager -f starting with Gnome Shell.
I think this happens because of
/etc/xdg/autostart/dde-file-manager-dialog-autostart.desktop
And a process
/usr/bin/dde-file-manager-daemon
is exists too.

Why? Strange.

**Comment by hualet** [comment]
When I said directly I mean what if you choose DDE and doesn't login to other sessions, is this happening ? 
dde-* processes are pulled up in other sessions sometimes, that's a known issue.

**Comment by avently** [comment]
I tried many times to load directly and found no issues with CPU.

**Comment by sbwtw** [comment]
It should be fixed in the latest version

**Comment by sayoojsamuel** [comment]
I still have this issue happening now.  I'm running Arch linux with Deepin 20 beta on top.  

A SIGTERM respawns the dock, and within 20 mins, it comes back to eating 100% CPU.

**Comment by Sophon96** [comment]
I'm having the same issue. I am also running Arch Linux with only Deepin. This seemed to have started happening after updating the Deepin packages.

**Comment by sayoojsamuel** [comment]
@Sophon96 deepin-dock version 5.2.0.14-1 seems to have resolved this problem. However, this issue was persistant till version 5.1.0.14-1.

**Comment by talesam** [comment]
**dde-dock using 100% CPU**
[alt text=""]!(https://cloud.talesam.org/apps/files_sharing/publicpreview/3KxBeM4j2Q5fY7J?x=1600&y=451&a=true&file=Captura%2520de%2520tela%2520de%25202020-11-28%252012-27-05.png&scalingup=0)
**version:** `deepin-dock 5.3.0.22-1`
Log file: https://cloud.talesam.org/s/BtXzBQMD5w2Pbxn

**Comment by sayoojsamuel** [comment]
@talesam you could maybe follow a temporary fix with cronjob to respawn the dde-dock when the cpu usage is high.  
Refer  https://github.com/linuxdeepin/dde-dock/issues/297#issuecomment-725394150.

**Comment by talesam** [comment]
> @talesam, talvez você possa seguir uma correção temporária com cronjob para reaparecer o dde-dock quando o uso da CPU estiver alto.
> Consulte [linuxdeepin / dde-dock # 297 (comentário)](https://github.com/linuxdeepin/dde-dock/issues/297#issuecomment-725394150) .

Thanks!
