### ISSUE TITLE
Alt-tab bug. 

### ISSUE THREAD

**Issue by eminSerin** [linuxdeepin/developer-center#494]
I encounter a bug when I try to open a background application from the dock. The program/window I tried to open does not appear on the screen and hangs. The only solution is to force close the window/application and re-open it.  The screen recording of the bug is below. Additionally, the issue is not a program specific, I have already confronted this bug with Matlab, Google Chrome, Spotify and even Deepin File Manager.

![deepin-screen-recorder_sun-awt-x11-xframepeer_20180319223827](https://user-images.githubusercontent.com/26147797/37624638-177ed45c-2bc9-11e8-9afb-c1ac460f73ff.gif)

I use fresh installed Deepin 15.5.

**Comment by sonald** [comment]
@eminSerin This has been fixed, we'll release an update later.

**Comment by eminSerin** [comment]
The problem still exists. 
Current version I use is as following: 
- Linux version 4.14.0-deepin2-amd64 (yangbo@deepin.com) (gcc version 6.3.0 20170321 (Debian 6.3.0-11)) #1 SMP PREEMPT Deepin 4.14.12-2 (2018-01-06)

**Comment by sonald** [comment]
15.6 will be released soon, and this should be included with a bunch of improvements.

**Comment by LuisTaloraWorldpay** [comment]
Hi. I have the same issue with DeepIn 15.8. Was this solved?
