### ISSUE TITLE
Deepin Appstore lags

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#674]
## Describe the bug
Deepin Store starts to lag after clicking to install button of any software.

## To Reproduce
1. Go to 'Deepin Store'
2. Click on 'install button of any program you see there'
3. And Deepin Appstore starts to lag. Can't click anything else until installation finishes.

## Expected behavior
After clicking the install button, should install the program and should let to navigate freely.

## Screenshots
A screenshot doesn't show the issue, so, I am leaving a video link: http://sendvid.com/t3huyxj1

### Distro & Version
Linux Deepin 15.8

### Related package version
deepin-appstore
Version: 5.1.2.3

**Comment by gokhanyildirimlar** [comment]
Installed Gnome with gdm and Deepin Appstore works as it should.

**Comment by hualet** [comment]
Maybe bug of deepin Window Manager.

**Comment by gokhanyildirimlar** [comment]
@hualet Issue no longer available, seems like it's fixed.

**Comment by hualet** [comment]
> @hualet Issue is no longer available. Seems like it's fixed.

OK, I'll close this issue then.

**Comment by gokhanyildirimlar** [comment]
@hualet I was using Linux Deepin in English when I said that the issue seems like fixed. I have done a fresh install today and chose the system language as Turkish. I saw that issue is still here in Turkish language. I don't know if this is connected with [this issue](https://github.com/linuxdeepin/developer-center/issues/675). Is it possible to open this issue one more again or should I open a new issue?

**Comment by gokhanyildirimlar** [comment]
I don't face this issue with the latest update. It looks like it has been solved.

**Comment by mjwhodur** [comment]
Hello guys, the issue still exists in Deepin in Polish, latest version.

**Comment by gokhanyildirimlar** [comment]
No questions, so, I close this one too.
