### ISSUE TITLE
File manager it's taking a long time to open after the update.

### ISSUE THREAD

**Issue by joaomarccos** [linuxdeepin/developer-center#840]
## Describe the bug

The file manager it's taking a long time to open.
## To Reproduce

Try open the deepin file manager from  

1. Go to desktop or terminal '...'
2. Click on file manager or put commando dde-file-manager on terminal
4. See the long time to open.

## Expected behavior

*Open more fast*

## Screenshots
![deepin-screen-recorder_select area_20190120144520](https://user-images.githubusercontent.com/7428221/51443031-46e29b80-1cc2-11e9-8ae1-8a176247f564.gif)

## Enviroments:
![image](https://user-images.githubusercontent.com/7428221/51443085-ac368c80-1cc2-11e9-99a9-9a1f7d1b44d9.png)

### Distro & Version

[Linux Deepin 15.9]

### Related package version

[dde-file-manager 4.7.4.4]

**Comment by joaomarccos** [comment]
Can you put here the steps to install please. I don't know install that from the build package. And when I tried install from source, don't works. I have failure messages in some files. Maybe I doing wrong things, so its better you show me the right way.

**Comment by BLumia** [comment]
Download every `.deb` package from https://ci.deepin.io/job/dde-file-manager/5866/ and do a `dpkg -i *.deb` is okay. After that, you can close all existing `dde-file-manager` instance and launch a new dde-file-manager instance to test if that works :)

**Comment by joaomarccos** [comment]
It was my first try. But a lot of dependencies not works with this version.

joao@joao-laptop:~/Downloads$ ls
dde-desktop_4.7.4.4_gerrit+41400_2_amd64.deb                   dde-file-manager-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb
dde-desktop-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb            libdde-file-manager_4.7.4.4_gerrit+41400_2_amd64.deb
dde-disk-mount-plugin_4.7.4.4_gerrit+41400_2_amd64.deb         libdde-file-manager-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb
dde-disk-mount-plugin-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb  libdde-file-manager-dev_4.7.4.4_gerrit+41400_2_amd64.deb
dde-file-manager_4.7.4.4_gerrit+41400_2_amd64.deb
joao@joao-laptop:~/Downloads$ sudo dpkg -i *.deb
[sudo] password for joao: 
dpkg: warning: downgrading dde-desktop from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
(Reading database ... 219208 files and directories currently installed.)
Preparing to unpack dde-desktop_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-desktop (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading dde-desktop-dbgsym from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack dde-desktop-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-desktop-dbgsym (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading dde-disk-mount-plugin from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack dde-disk-mount-plugin_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-disk-mount-plugin (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading dde-disk-mount-plugin-dbgsym from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack dde-disk-mount-plugin-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-disk-mount-plugin-dbgsym (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading dde-file-manager from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack dde-file-manager_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-file-manager (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading dde-file-manager-dbgsym from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack dde-file-manager-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-file-manager-dbgsym (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading libdde-file-manager:amd64 from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack libdde-file-manager_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking libdde-file-manager:amd64 (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading libdde-file-manager-dbgsym:amd64 from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack libdde-file-manager-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking libdde-file-manager-dbgsym:amd64 (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading libdde-file-manager-dev from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack libdde-file-manager-dev_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking libdde-file-manager-dev (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: dependency problems prevent configuration of dde-desktop:
 dde-desktop depends on libdtkwidget2 (>= 2.0.9.14+r190121110917+gc1a2285); however:
  Version of libdtkwidget2:amd64 on system is 2.0.9.14-1.

dpkg: error processing package dde-desktop (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dde-desktop-dbgsym:
 dde-desktop-dbgsym depends on dde-desktop (= 4.7.4.4~gerrit+41400~2); however:
  Package dde-desktop is not configured yet.

dpkg: error processing package dde-desktop-dbgsym (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dde-disk-mount-plugin:
 dde-disk-mount-plugin depends on libdtkwidget2 (>= 2.0.9.14+r190121110917+gc1a2285); however:
  Version of libdtkwidget2:amd64 on system is 2.0.9.14-1.

dpkg: error processing package dde-disk-mount-plugin (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dde-disk-mount-plugin-dbgsym:
 dde-disk-mount-plugin-dbgsym depends on dde-disk-mount-plugin (= 4.7.4.4~gerrit+41400~2); however:
  Package dde-disk-mount-plugin is not configured yet.

dpkg: error processing package dde-disk-mount-plugin-dbgsym (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dde-file-manager:
 dde-file-manager depends on libdtkwidget2 (>= 2.0.9.14+r190121110917+gc1a2285); however:
  Version of libdtkwidget2:amd64 on system is 2.0.9.14-1.

dpkg: error processing package dde-file-manager (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dde-file-manager-dbgsym:
 dde-file-manager-dbgsym depends on dde-file-manager (= 4.7.4.4~gerrit+41400~2); however:
  Package dde-file-manager is not configured yet.

dpkg: error processing package dde-file-manager-dbgsym (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libdde-file-manager:amd64:
 libdde-file-manager:amd64 depends on libdtkcore2 (>= 2.0.9.14+r190104135224+g86dbd50); however:
  Version of libdtkcore2:amd64 on system is 2.0.9.14-1.
 libdde-file-manager:amd64 depends on libdtkwidget2 (>= 2.0.9.14+r190121110917+gc1a2285); however:
  Version of libdtkwidget2:amd64 on system is 2.0.9.14-1.

dpkg: error processing package libdde-file-manager:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libdde-file-manager-dbgsym:amd64:
 libdde-file-manager-dbgsym:amd64 depends on libdde-file-manager (= 4.7.4.4~gerrit+41400~2); however:
  Package libdde-file-manager:amd64 is not configured yet.

dpkg: error processing package libdde-file-manager-dbgsym:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libdde-file-manager-dev:
 libdde-file-manager-dev depends on libdde-file-manager (= 4.7.4.4~gerrit+41400~2); however:
  Package libdde-file-manager:amd64 is not configured yet.

dpkg: error processing package libdde-file-manager-dev (--install):
 dependency problems - leaving unconfigured
Processing triggers for lastore-daemon (0.13.0-2) ...
Processing triggers for desktop-file-utils (0.23-3) ...
Processing triggers for bamfdaemon (0.5.3-2+b1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.60) ...
Processing triggers for dbus (1.12.8-2) ...
Processing triggers for libc-bin (2.27-3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 dde-desktop
 dde-desktop-dbgsym
 dde-disk-mount-plugin
 dde-disk-mount-plugin-dbgsym
 dde-file-manager
 dde-file-manager-dbgsym
 libdde-file-manager:amd64
 libdde-file-manager-dbgsym:amd64
 libdde-file-manager-dev

**Comment by joaomarccos** [comment]
It was my first try, But has encountered a lot of warning about dependencies conflict. I think was not installed correctly.

log:

`joao@joao-laptop:~/Downloads$ ls
dde-desktop_4.7.4.4_gerrit+41400_2_amd64.deb                   dde-file-manager-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb
dde-desktop-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb            libdde-file-manager_4.7.4.4_gerrit+41400_2_amd64.deb
dde-disk-mount-plugin_4.7.4.4_gerrit+41400_2_amd64.deb         libdde-file-manager-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb
dde-disk-mount-plugin-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb  libdde-file-manager-dev_4.7.4.4_gerrit+41400_2_amd64.deb
dde-file-manager_4.7.4.4_gerrit+41400_2_amd64.deb
joao@joao-laptop:~/Downloads$ sudo dpkg -i *.deb
[sudo] password for joao: 
dpkg: warning: downgrading dde-desktop from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
(Reading database ... 219208 files and directories currently installed.)
Preparing to unpack dde-desktop_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-desktop (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading dde-desktop-dbgsym from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack dde-desktop-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-desktop-dbgsym (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading dde-disk-mount-plugin from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack dde-disk-mount-plugin_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-disk-mount-plugin (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading dde-disk-mount-plugin-dbgsym from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack dde-disk-mount-plugin-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-disk-mount-plugin-dbgsym (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading dde-file-manager from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack dde-file-manager_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-file-manager (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading dde-file-manager-dbgsym from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack dde-file-manager-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking dde-file-manager-dbgsym (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading libdde-file-manager:amd64 from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack libdde-file-manager_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking libdde-file-manager:amd64 (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading libdde-file-manager-dbgsym:amd64 from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack libdde-file-manager-dbgsym_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking libdde-file-manager-dbgsym:amd64 (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: warning: downgrading libdde-file-manager-dev from 4.7.4.4-1 to 4.7.4.4~gerrit+41400~2
Preparing to unpack libdde-file-manager-dev_4.7.4.4_gerrit+41400_2_amd64.deb ...
Unpacking libdde-file-manager-dev (4.7.4.4~gerrit+41400~2) over (4.7.4.4-1) ...
dpkg: dependency problems prevent configuration of dde-desktop:
 dde-desktop depends on libdtkwidget2 (>= 2.0.9.14+r190121110917+gc1a2285); however:
  Version of libdtkwidget2:amd64 on system is 2.0.9.14-1.

dpkg: error processing package dde-desktop (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dde-desktop-dbgsym:
 dde-desktop-dbgsym depends on dde-desktop (= 4.7.4.4~gerrit+41400~2); however:
  Package dde-desktop is not configured yet.

dpkg: error processing package dde-desktop-dbgsym (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dde-disk-mount-plugin:
 dde-disk-mount-plugin depends on libdtkwidget2 (>= 2.0.9.14+r190121110917+gc1a2285); however:
  Version of libdtkwidget2:amd64 on system is 2.0.9.14-1.

dpkg: error processing package dde-disk-mount-plugin (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dde-disk-mount-plugin-dbgsym:
 dde-disk-mount-plugin-dbgsym depends on dde-disk-mount-plugin (= 4.7.4.4~gerrit+41400~2); however:
  Package dde-disk-mount-plugin is not configured yet.

dpkg: error processing package dde-disk-mount-plugin-dbgsym (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dde-file-manager:
 dde-file-manager depends on libdtkwidget2 (>= 2.0.9.14+r190121110917+gc1a2285); however:
  Version of libdtkwidget2:amd64 on system is 2.0.9.14-1.

dpkg: error processing package dde-file-manager (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of dde-file-manager-dbgsym:
 dde-file-manager-dbgsym depends on dde-file-manager (= 4.7.4.4~gerrit+41400~2); however:
  Package dde-file-manager is not configured yet.

dpkg: error processing package dde-file-manager-dbgsym (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libdde-file-manager:amd64:
 libdde-file-manager:amd64 depends on libdtkcore2 (>= 2.0.9.14+r190104135224+g86dbd50); however:
  Version of libdtkcore2:amd64 on system is 2.0.9.14-1.
 libdde-file-manager:amd64 depends on libdtkwidget2 (>= 2.0.9.14+r190121110917+gc1a2285); however:
  Version of libdtkwidget2:amd64 on system is 2.0.9.14-1.

dpkg: error processing package libdde-file-manager:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libdde-file-manager-dbgsym:amd64:
 libdde-file-manager-dbgsym:amd64 depends on libdde-file-manager (= 4.7.4.4~gerrit+41400~2); however:
  Package libdde-file-manager:amd64 is not configured yet.

dpkg: error processing package libdde-file-manager-dbgsym:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libdde-file-manager-dev:
 libdde-file-manager-dev depends on libdde-file-manager (= 4.7.4.4~gerrit+41400~2); however:
  Package libdde-file-manager:amd64 is not configured yet.

dpkg: error processing package libdde-file-manager-dev (--install):
 dependency problems - leaving unconfigured
Processing triggers for lastore-daemon (0.13.0-2) ...
Processing triggers for desktop-file-utils (0.23-3) ...
Processing triggers for bamfdaemon (0.5.3-2+b1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.60) ...
Processing triggers for dbus (1.12.8-2) ...
Processing triggers for libc-bin (2.27-3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 dde-desktop
 dde-desktop-dbgsym
 dde-disk-mount-plugin
 dde-disk-mount-plugin-dbgsym
 dde-file-manager
 dde-file-manager-dbgsym
 libdde-file-manager:amd64
 libdde-file-manager-dbgsym:amd64
 libdde-file-manager-dev
`

**Comment by joaomarccos** [comment]
However I tried open a new instance and continues with the same problem. And is not only on initializing, occur when open folders as well. On previous version (before update to 15.9) all works properly.

Note I'm using SSD. And the diagnostics are OK.

**Comment by BLumia** [comment]
There will have a new update in the upcoming 1 or 2 days, please try the new version after the update release and checkout if this issue still happening, thx.

**Comment by keybreak** [comment]
Confirm, still happens on Manjaro Deepin compared to vanilla manjaro-deepin-18.0.2-stable-x86_64.iso it's noticeably more time to open for example deepin file manager, i believe rest of programs also.

Any program first launch time become 1-1.5 seconds more, on older machine with hard drive 5400rpm it’s pretty noticeable, on SSD not really much differencce)

Suspect it could probably related more to deepin-turbo, than dde-file-manager?

**Comment by aiamuzz** [comment]
can't put a finger to it ... but off late even i have seen some instances where the file manager has been very slow or crashed !!!

**Comment by BLumia** [comment]
The `4.7.6` version should already solved this issue, please check if the package maintainer have updated the `dde-file-manager` package or not, update the package and see if it can solve your problem.

If the most recent release still have the problem, a log file for that would be very helpful.

**Comment by keybreak** [comment]
On Manjaro Deepin it's still deepin-file-manager 1:4.7.5-1, v4.7.6 not yet available, will test it and report result when it will arrive!

**Comment by BLumia** [comment]
> Confirm, still happens on Manjaro Deepin compared to vanilla manjaro-deepin-18.0.2-stable-x86_64.iso it's noticeably more time to open for example deepin file manager, i believe rest of programs also.
> 
> Any program first launch time become 1-1.5 seconds more, on older machine with hard drive 5400rpm it’s pretty noticeable, on SSD not really much differencce)
> 
> Suspect it could probably related more to deepin-turbo, than dde-file-manager?

Seems it's another topic since this issue is caused by the file manager's "recent file" feature. DFM used to use the wrong way to do monitoring and parsing the `recently-used.xbel` file. That's the main reason for @joaomarccos 's case. Maybe it's better to close this issue and start another one to discuss about the launch speed for all common DDE applications :)

**Comment by keybreak** [comment]
Wonder if this issue happened also if recent files was disabled in settings?

Done https://github.com/linuxdeepin/developer-center/issues/900

**Comment by BLumia** [comment]
> Wonder if this issue happened also if recent files was disabled in settings?
> 
> Done #900

Yep, the related code should be refactored, but the last fix for this issue should solve the issue caused by the file watcher which is the main reason caused this issue (once any file changed at the same folder as `recently-used.xbel`, it will try re-parse the `recently-used.xbel` file again, what is a bad implementation and it's fixed in the previous update).

Closing this one now :)

**Comment by rubenvdham** [comment]
I'm still facing this issue. The file manager takes 10 seconds to open. When one instance is launched, other ones launch instantly; like it used to be. The issue seems only to occur when no instance of File-manager is running. 
I'm running: community/deepin-file-manager 1:4.7.6-2 (deepin)

**Comment by BLumia** [comment]
> I'm still facing this issue. The file manager takes 10 seconds to open. When one instance is launched, other ones launch instantly; like it used to be. The issue seems only to occur when no instance of File-manager is running.
> I'm running: community/deepin-file-manager 1:4.7.6-2 (deepin)

Hi and thx for reporting issue, how many items are now under the "Recent file" catalog  (url `recent:///`)? Will the first instance launch speed become it used to be if you clear all of them from the recent file catalog (select all and delete them, don't worry, it will only remove the recent history, won't delete your original file)?

**Comment by rubenvdham** [comment]
@BLumia 996 items. (some in folders of 20K files). I guess IO may have been an issue. After removal everything is snappy again. Thanks!

**Comment by BLumia** [comment]
> @BLumia 996 items. (some in folders of 20K files). I guess IO may have been an issue. After removal everything is snappy again. Thanks!

This part of code will be refactored later, You can tracking the state in https://github.com/linuxdeepin/internal-discussion/issues/977 :)

**Comment by shao82456** [comment]
so did i. when open my deepin-file-manager or some app try call it, it's a long time wait. and i really want to 
remove it but can't,because the dependency of desktop

**Comment by BLumia** [comment]
> when open my deepin-file-manager or some app try call it, it's a long time wait. and i really want to
> remove it but can't,because the dependency of desktop

Could you provide the log file so we can see why it launch slow on your machine?

Feel free to open a new issue at [Developer-Center](https://github.com/linuxdeepin/developer-center/issues) and don't forget to provide the details may needed.

**Comment by shao82456** [comment]
first, my os is manjara with deepin desktop environment. every thing is ok but after like 3-4 month ago it begin really slow to open.it's shows exactly same as joaomarccos,i don't know what should i provide to help solve, but from outside of the box,it's exactly same.

**Comment by shao82456** [comment]
it's looks like because the follow question
Error creating proxy: Error calling StartServiceByName for org.gtk.vfs.GPhoto2VolumeMonitor: Timeout was reached (g-io-error-quark, 24)

**Comment by BLumia** [comment]
> it's looks like because the follow question
> Error creating proxy: Error calling StartServiceByName for org.gtk.vfs.GPhoto2VolumeMonitor: Timeout was reached (g-io-error-quark, 24)

Could you provide the full log in a new issue? Since this is not related in this issue (which caused by the sync load of recent file data processing). Thanks.

**Comment by AmigaBlitter** [comment]
Same issue for me. When i call the file manager and when i call the shutdown or reboot option. It' takes many seconds to both to appear on screen.
Deepin 20 and Ubuntu 20.10
